//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Mappings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Monasteries = new HashSet<Monasteries>();
            this.Rivers = new HashSet<Rivers>();
        }
    
        public string CountryCode { get; set; }
        public string IsoCode { get; set; }
        public string CountryName { get; set; }
        public string CurrencyCode { get; set; }
        public string ContinentCode { get; set; }
        public int Population { get; set; }
        public int AreaInSqKm { get; set; }
        public string Capital { get; set; }
    
        public virtual Continents Continents { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual ICollection<Monasteries> Monasteries { get; set; }
        public virtual ICollection<Rivers> Rivers { get; set; }
    }
}
