//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.InternationalMatches = new HashSet<InternationalMatches>();
            this.InternationalMatches1 = new HashSet<InternationalMatches>();
            this.Leagues = new HashSet<Leagues>();
            this.Teams = new HashSet<Teams>();
        }
    
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<int> AreaSqKm { get; set; }
        public string Capital { get; set; }
    
        public virtual ICollection<InternationalMatches> InternationalMatches { get; set; }
        public virtual ICollection<InternationalMatches> InternationalMatches1 { get; set; }
        public virtual ICollection<Leagues> Leagues { get; set; }
        public virtual ICollection<Teams> Teams { get; set; }
    }
}
