//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public Teams()
        {
            this.TeamMatches = new HashSet<TeamMatches>();
            this.TeamMatches1 = new HashSet<TeamMatches>();
            this.Leagues = new HashSet<Leagues>();
        }
    
        public int Id { get; set; }
        public string TeamName { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<TeamMatches> TeamMatches { get; set; }
        public virtual ICollection<TeamMatches> TeamMatches1 { get; set; }
        public virtual ICollection<Leagues> Leagues { get; set; }
    }
}
